### ISSUE TITLE
Blog Resource for Mozilla Quality Assurance - Bug Verification day

### ISSUE THREAD

**Issue by SurenVino** [SOHW/Blogs#13]
hey hai,
This is Surentharan. I am from Mozilla Tamilnadu Community. I am one of the QA Co-ordinators of Mozilla India Community. I Would Like to add Blog resource for Bug verification so that it can help new contributors to make their contribution easier. The Blog which I would like to add will acts as a reference for their contribution and it includes step by step procedure

**Comment by FahimaZulfath** [comment]
@SurenVino thanks for taking time to contribute. Yaay!! go ahead and add it. Eagerly waiting to merge your PR. ⭐️ 

 Have a look on [SOHW wiki](https://github.com/SOHW/wiki) for forking, working with repo files, etc. If you want any help, let me know. 😄
